/********************************************************************
*
* C66SS1_INTROUTER0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef SDLR_C66SS1_INTROUTER0_INTERRUPT_MAP_H_
#define SDLR_C66SS1_INTROUTER0_INTERRUPT_MAP_H_

#include <sdlr.h>
#include <tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: C66SS1_INTROUTER0
*/

#define SDLR_C66SS1_INTROUTER0_IN_TIMER0_INTR_PEND_0                                               (1U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER1_INTR_PEND_0                                               (2U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER2_INTR_PEND_0                                               (3U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER3_INTR_PEND_0                                               (4U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER4_INTR_PEND_0                                               (5U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER5_INTR_PEND_0                                               (6U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER6_INTR_PEND_0                                               (7U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER7_INTR_PEND_0                                               (8U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER8_INTR_PEND_0                                               (9U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER9_INTR_PEND_0                                               (10U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER10_INTR_PEND_0                                              (11U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER11_INTR_PEND_0                                              (12U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER16_INTR_PEND_0                                              (13U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER17_INTR_PEND_0                                              (14U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER18_INTR_PEND_0                                              (15U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER19_INTR_PEND_0                                              (16U)
#define SDLR_C66SS1_INTROUTER0_IN_MCSPI3_INTR_SPI_0                                                (17U)
#define SDLR_C66SS1_INTROUTER0_IN_MCSPI4_INTR_SPI_0                                                (18U)
#define SDLR_C66SS1_INTROUTER0_IN_MCSPI5_INTR_SPI_0                                                (19U)
#define SDLR_C66SS1_INTROUTER0_IN_MCSPI6_INTR_SPI_0                                                (20U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN2_MCANSS_MCAN_LVL_INT_0                                      (21U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN2_MCANSS_MCAN_LVL_INT_1                                      (22U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN2_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (23U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN3_MCANSS_MCAN_LVL_INT_0                                      (24U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN3_MCANSS_MCAN_LVL_INT_1                                      (25U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN3_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (26U)
#define SDLR_C66SS1_INTROUTER0_IN_I2C3_POINTRPEND_0                                                (27U)
#define SDLR_C66SS1_INTROUTER0_IN_I2C4_POINTRPEND_0                                                (28U)
#define SDLR_C66SS1_INTROUTER0_IN_I2C5_POINTRPEND_0                                                (29U)
#define SDLR_C66SS1_INTROUTER0_IN_I2C6_POINTRPEND_0                                                (30U)
#define SDLR_C66SS1_INTROUTER0_IN_GLUELOGIC_SOCA_INT_GLUE_SOCA_INT_0                               (31U)
#define SDLR_C66SS1_INTROUTER0_IN_GLUELOGIC_SOCB_INT_GLUE_SOCB_INT_0                               (32U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM0_EPWM_ETINT_0                                             (33U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM1_EPWM_ETINT_0                                             (34U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM2_EPWM_ETINT_0                                             (35U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM3_EPWM_ETINT_0                                             (36U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM4_EPWM_ETINT_0                                             (37U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM5_EPWM_ETINT_0                                             (38U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM0_EPWM_TRIPZINT_0                                          (39U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM1_EPWM_TRIPZINT_0                                          (40U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM2_EPWM_TRIPZINT_0                                          (41U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM3_EPWM_TRIPZINT_0                                          (42U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM4_EPWM_TRIPZINT_0                                          (43U)
#define SDLR_C66SS1_INTROUTER0_IN_EHRPWM5_EPWM_TRIPZINT_0                                          (44U)
#define SDLR_C66SS1_INTROUTER0_IN_ECAP0_ECAP_INT_0                                                 (45U)
#define SDLR_C66SS1_INTROUTER0_IN_ECAP1_ECAP_INT_0                                                 (46U)
#define SDLR_C66SS1_INTROUTER0_IN_ECAP2_ECAP_INT_0                                                 (47U)
#define SDLR_C66SS1_INTROUTER0_IN_EQEP0_EQEP_INT_0                                                 (48U)
#define SDLR_C66SS1_INTROUTER0_IN_EQEP1_EQEP_INT_0                                                 (49U)
#define SDLR_C66SS1_INTROUTER0_IN_EQEP2_EQEP_INT_0                                                 (50U)
#define SDLR_C66SS1_INTROUTER0_IN_UART3_USART_IRQ_0                                                (51U)
#define SDLR_C66SS1_INTROUTER0_IN_UART4_USART_IRQ_0                                                (52U)
#define SDLR_C66SS1_INTROUTER0_IN_UART5_USART_IRQ_0                                                (53U)
#define SDLR_C66SS1_INTROUTER0_IN_UART6_USART_IRQ_0                                                (54U)
#define SDLR_C66SS1_INTROUTER0_IN_UART7_USART_IRQ_0                                                (55U)
#define SDLR_C66SS1_INTROUTER0_IN_UART8_USART_IRQ_0                                                (56U)
#define SDLR_C66SS1_INTROUTER0_IN_UART9_USART_IRQ_0                                                (57U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN4_MCANSS_MCAN_LVL_INT_0                                      (58U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN4_MCANSS_MCAN_LVL_INT_1                                      (59U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN4_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (60U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN5_MCANSS_MCAN_LVL_INT_0                                      (61U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN5_MCANSS_MCAN_LVL_INT_1                                      (62U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN5_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (63U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN6_MCANSS_MCAN_LVL_INT_0                                      (64U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN6_MCANSS_MCAN_LVL_INT_1                                      (65U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN6_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (66U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN7_MCANSS_MCAN_LVL_INT_0                                      (67U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN7_MCANSS_MCAN_LVL_INT_1                                      (68U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN7_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (69U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN8_MCANSS_MCAN_LVL_INT_0                                      (70U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN8_MCANSS_MCAN_LVL_INT_1                                      (71U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN8_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (72U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN9_MCANSS_MCAN_LVL_INT_0                                      (73U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN9_MCANSS_MCAN_LVL_INT_1                                      (74U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN9_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (75U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN10_MCANSS_MCAN_LVL_INT_0                                     (76U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN10_MCANSS_MCAN_LVL_INT_1                                     (77U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN10_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (78U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN11_MCANSS_MCAN_LVL_INT_0                                     (79U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN11_MCANSS_MCAN_LVL_INT_1                                     (80U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN11_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (81U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN12_MCANSS_MCAN_LVL_INT_0                                     (82U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN12_MCANSS_MCAN_LVL_INT_1                                     (83U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN12_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (84U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN13_MCANSS_MCAN_LVL_INT_0                                     (85U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN13_MCANSS_MCAN_LVL_INT_1                                     (86U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN13_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (87U)
#define SDLR_C66SS1_INTROUTER0_IN_GPU0_MISC_0_IRQ_0                                                (89U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_376                               (97U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_377                               (98U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_378                               (99U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_379                               (100U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_380                               (101U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_381                               (102U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_382                               (103U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_383                               (104U)
#define SDLR_C66SS1_INTROUTER0_IN_DSS0_DSS_INST0_DISPC_FUNC_IRQ_PROC0_0                            (105U)
#define SDLR_C66SS1_INTROUTER0_IN_DSS0_DSS_INST0_DISPC_FUNC_IRQ_PROC1_0                            (106U)
#define SDLR_C66SS1_INTROUTER0_IN_DSS0_DSS_INST0_DISPC_SECURE_IRQ_PROC0_0                          (107U)
#define SDLR_C66SS1_INTROUTER0_IN_DSS0_DSS_INST0_DISPC_SECURE_IRQ_PROC1_0                          (108U)
#define SDLR_C66SS1_INTROUTER0_IN_DSS0_DSS_INST0_DISPC_SAFETY_ERROR_IRQ_PROC0_0                    (109U)
#define SDLR_C66SS1_INTROUTER0_IN_DSS0_DSS_INST0_DISPC_SAFETY_ERROR_IRQ_PROC1_0                    (110U)
#define SDLR_C66SS1_INTROUTER0_IN_DMPAC0_INTD_0_SYSTEM_INTR_LEVEL_0                                (111U)
#define SDLR_C66SS1_INTROUTER0_IN_DMPAC0_INTD_0_SYSTEM_INTR_LEVEL_1                                (112U)
#define SDLR_C66SS1_INTROUTER0_IN_GLUELOGIC_GPU_GPIO_REQACK_GLUE_GPU_GPIO_REQINT_LVL_0             (115U)
#define SDLR_C66SS1_INTROUTER0_IN_GLUELOGIC_GPU_GPIO_REQACK_GLUE_GPU_GPIO_ACKINT_LVL_0             (116U)
#define SDLR_C66SS1_INTROUTER0_IN_CPSW0_STAT_PEND_0                                                (117U)
#define SDLR_C66SS1_INTROUTER0_IN_CPSW0_MDIO_PEND_0                                                (118U)
#define SDLR_C66SS1_INTROUTER0_IN_CPSW0_EVNT_PEND_0                                                (119U)
#define SDLR_C66SS1_INTROUTER0_IN_SA2_UL0_SA_UL_PKA_0                                              (120U)
#define SDLR_C66SS1_INTROUTER0_IN_SA2_UL0_SA_UL_TRNG_0                                             (121U)
#define SDLR_C66SS1_INTROUTER0_IN_ESM0_ESM_INT_LOW_LVL_0                                           (122U)
#define SDLR_C66SS1_INTROUTER0_IN_ESM0_ESM_INT_HI_LVL_0                                            (123U)
#define SDLR_C66SS1_INTROUTER0_IN_ESM0_ESM_INT_CFG_LVL_0                                           (124U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_40                                          (128U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_41                                          (129U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_42                                          (130U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_43                                          (131U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_44                                          (132U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_45                                          (133U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_46                                          (134U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_47                                          (135U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_48                                          (136U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_49                                          (137U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_50                                          (138U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_51                                          (139U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_52                                          (140U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_53                                          (141U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_54                                          (142U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_55                                          (143U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_56                                          (144U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_57                                          (145U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_58                                          (146U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_59                                          (147U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_60                                          (148U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_61                                          (149U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_62                                          (150U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_63                                          (151U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_0                                  (152U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_1                                  (153U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_2                                  (154U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_3                                  (155U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_4                                  (156U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_5                                  (157U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_6                                  (158U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_7                                  (159U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_0                                  (160U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_1                                  (161U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_2                                  (162U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_3                                  (163U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_4                                  (164U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_5                                  (165U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_6                                  (166U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_7                                  (167U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_TX_SOF_INTR_REQ_0                                 (168U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_TX_SOF_INTR_REQ_1                                 (169U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_RX_SOF_INTR_REQ_0                                 (170U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG0_PR1_RX_SOF_INTR_REQ_1                                 (171U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_TX_SOF_INTR_REQ_0                                 (172U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_TX_SOF_INTR_REQ_1                                 (173U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_RX_SOF_INTR_REQ_0                                 (174U)
#define SDLR_C66SS1_INTROUTER0_IN_PRU_ICSSG1_PR1_RX_SOF_INTR_REQ_1                                 (175U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_IRQ_0                                                       (176U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_IRQ_1                                                       (177U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_IRQ_2                                                       (178U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_IRQ_3                                                       (179U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_IRQ_4                                                       (180U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_IRQ_5                                                       (181U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_IRQ_6                                                       (182U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_IRQ_7                                                       (183U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_IRQ_0                                                       (184U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_IRQ_1                                                       (185U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_IRQ_2                                                       (186U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_IRQ_3                                                       (187U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_IRQ_4                                                       (188U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_IRQ_5                                                       (189U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_IRQ_6                                                       (190U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_IRQ_7                                                       (191U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_OTGIRQ_0                                                    (200U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_OTGIRQ_0                                                    (201U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_LEGACY_PULSE_0                                        (203U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_DOWNSTREAM_PULSE_0                                    (204U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_FLR_PULSE_0                                           (205U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_PHY_LEVEL_0                                           (206U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_LOCAL_LEVEL_0                                         (207U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_ERROR_PULSE_0                                         (208U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_LINK_STATE_PULSE_0                                    (209U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_PWR_STATE_PULSE_0                                     (210U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_PTM_VALID_PULSE_0                                     (211U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_HOT_RESET_PULSE_0                                     (212U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE0_PCIE_CPTS_PEND_0                                           (213U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_LEGACY_PULSE_0                                        (215U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_DOWNSTREAM_PULSE_0                                    (216U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_FLR_PULSE_0                                           (217U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_PHY_LEVEL_0                                           (218U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_LOCAL_LEVEL_0                                         (219U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_ERROR_PULSE_0                                         (220U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_LINK_STATE_PULSE_0                                    (221U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_PWR_STATE_PULSE_0                                     (222U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_PTM_VALID_PULSE_0                                     (223U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_HOT_RESET_PULSE_0                                     (224U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE1_PCIE_CPTS_PEND_0                                           (225U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_LEGACY_PULSE_0                                        (227U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_DOWNSTREAM_PULSE_0                                    (228U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_FLR_PULSE_0                                           (229U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_PHY_LEVEL_0                                           (230U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_LOCAL_LEVEL_0                                         (231U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_ERROR_PULSE_0                                         (232U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_LINK_STATE_PULSE_0                                    (233U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_PWR_STATE_PULSE_0                                     (234U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_PTM_VALID_PULSE_0                                     (235U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_HOT_RESET_PULSE_0                                     (236U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE2_PCIE_CPTS_PEND_0                                           (237U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_LEGACY_PULSE_0                                        (239U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_DOWNSTREAM_PULSE_0                                    (240U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_FLR_PULSE_0                                           (241U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_PHY_LEVEL_0                                           (242U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_LOCAL_LEVEL_0                                         (243U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_ERROR_PULSE_0                                         (244U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_LINK_STATE_PULSE_0                                    (245U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_PWR_STATE_PULSE_0                                     (246U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_PTM_VALID_PULSE_0                                     (247U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_HOT_RESET_PULSE_0                                     (248U)
#define SDLR_C66SS1_INTROUTER0_IN_PCIE3_PCIE_CPTS_PEND_0                                           (249U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_16                    (253U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_17                    (254U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_18                    (255U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_19                    (256U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_20                    (257U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_21                    (258U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_22                    (259U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_23                    (260U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_24                    (261U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_25                    (262U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_26                    (263U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_27                    (264U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_28                    (265U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_29                    (266U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_30                    (267U)
#define SDLR_C66SS1_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_31                    (268U)
#define SDLR_C66SS1_INTROUTER0_IN_VPAC0_INTD_0_SYSTEM_INTR_LEVEL_0                                 (269U)
#define SDLR_C66SS1_INTROUTER0_IN_VPAC0_INTD_0_SYSTEM_INTR_LEVEL_1                                 (270U)
#define SDLR_C66SS1_INTROUTER0_IN_VPAC0_INTD_0_SYSTEM_INTR_LEVEL_2                                 (271U)
#define SDLR_C66SS1_INTROUTER0_IN_VPAC0_INTD_0_SYSTEM_INTR_LEVEL_3                                 (272U)
#define SDLR_C66SS1_INTROUTER0_IN_VPAC0_INTD_0_SYSTEM_INTR_LEVEL_4                                 (273U)
#define SDLR_C66SS1_INTROUTER0_IN_VPAC0_INTD_0_SYSTEM_INTR_LEVEL_5                                 (274U)
#define SDLR_C66SS1_INTROUTER0_IN_USB0_HOST_SYSTEM_ERROR_0                                         (277U)
#define SDLR_C66SS1_INTROUTER0_IN_USB1_HOST_SYSTEM_ERROR_0                                         (278U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_CPSW0_STAT_PEND_0                                            (280U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_CPSW0_MDIO_PEND_0                                            (281U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_CPSW0_EVNT_PEND_0                                            (282U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER0_INTR_PEND_0                                           (284U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER1_INTR_PEND_0                                           (285U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER2_INTR_PEND_0                                           (286U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER3_INTR_PEND_0                                           (287U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER4_INTR_PEND_0                                           (288U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER5_INTR_PEND_0                                           (289U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER6_INTR_PEND_0                                           (290U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER7_INTR_PEND_0                                           (291U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER8_INTR_PEND_0                                           (292U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_TIMER9_INTR_PEND_0                                           (293U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_ESM0_ESM_INT_LOW_LVL_0                                       (296U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_ESM0_ESM_INT_HI_LVL_0                                        (297U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_ESM0_ESM_INT_CFG_LVL_0                                       (298U)
#define SDLR_C66SS1_INTROUTER0_IN_WKUP_ESM0_ESM_INT_LOW_LVL_0                                      (299U)
#define SDLR_C66SS1_INTROUTER0_IN_WKUP_ESM0_ESM_INT_HI_LVL_0                                       (300U)
#define SDLR_C66SS1_INTROUTER0_IN_WKUP_ESM0_ESM_INT_CFG_LVL_0                                      (301U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER12_INTR_PEND_0                                              (304U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER13_INTR_PEND_0                                              (305U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER14_INTR_PEND_0                                              (306U)
#define SDLR_C66SS1_INTROUTER0_IN_TIMER15_INTR_PEND_0                                              (307U)
#define SDLR_C66SS1_INTROUTER0_IN_RTI25_INTR_WWD_0                                                 (308U)
#define SDLR_C66SS1_INTROUTER0_IN_CTRL_MMR0_IPC_SET7_IPC_SET_IPCFG_0                               (309U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP0_REC_INTR_PEND_0                                           (310U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP1_REC_INTR_PEND_0                                           (311U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP2_REC_INTR_PEND_0                                           (312U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP3_REC_INTR_PEND_0                                           (313U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP4_REC_INTR_PEND_0                                           (314U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP5_REC_INTR_PEND_0                                           (315U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP6_REC_INTR_PEND_0                                           (316U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP7_REC_INTR_PEND_0                                           (317U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP8_REC_INTR_PEND_0                                           (318U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP9_REC_INTR_PEND_0                                           (319U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP10_REC_INTR_PEND_0                                          (320U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP11_REC_INTR_PEND_0                                          (321U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP0_XMIT_INTR_PEND_0                                          (322U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP1_XMIT_INTR_PEND_0                                          (323U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP2_XMIT_INTR_PEND_0                                          (324U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP3_XMIT_INTR_PEND_0                                          (325U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP4_XMIT_INTR_PEND_0                                          (326U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP5_XMIT_INTR_PEND_0                                          (327U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP6_XMIT_INTR_PEND_0                                          (328U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP7_XMIT_INTR_PEND_0                                          (329U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP8_XMIT_INTR_PEND_0                                          (330U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP9_XMIT_INTR_PEND_0                                          (331U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP10_XMIT_INTR_PEND_0                                         (332U)
#define SDLR_C66SS1_INTROUTER0_IN_MCASP11_XMIT_INTR_PEND_0                                         (333U)
#define SDLR_C66SS1_INTROUTER0_IN_AASRC0_INFIFO_LEVEL_0                                            (334U)
#define SDLR_C66SS1_INTROUTER0_IN_AASRC0_INGROUP_LEVEL_0                                           (335U)
#define SDLR_C66SS1_INTROUTER0_IN_AASRC0_OUTFIFO_LEVEL_0                                           (336U)
#define SDLR_C66SS1_INTROUTER0_IN_AASRC0_OUTGROUP_LEVEL_0                                          (337U)
#define SDLR_C66SS1_INTROUTER0_IN_AASRC0_ERR_LEVEL_0                                               (338U)
#define SDLR_C66SS1_INTROUTER0_IN_I3C0_I3C__INT_0                                                  (339U)
#define SDLR_C66SS1_INTROUTER0_IN_MCSPI0_INTR_SPI_0                                                (340U)
#define SDLR_C66SS1_INTROUTER0_IN_MCSPI1_INTR_SPI_0                                                (341U)
#define SDLR_C66SS1_INTROUTER0_IN_MCSPI2_INTR_SPI_0                                                (342U)
#define SDLR_C66SS1_INTROUTER0_IN_MCSPI7_INTR_SPI_0                                                (343U)
#define SDLR_C66SS1_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_12                                         (344U)
#define SDLR_C66SS1_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_13                                         (345U)
#define SDLR_C66SS1_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_14                                         (346U)
#define SDLR_C66SS1_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_15                                         (347U)
#define SDLR_C66SS1_INTROUTER0_IN_I2C0_POINTRPEND_0                                                (348U)
#define SDLR_C66SS1_INTROUTER0_IN_I2C1_POINTRPEND_0                                                (349U)
#define SDLR_C66SS1_INTROUTER0_IN_I2C2_POINTRPEND_0                                                (350U)
#define SDLR_C66SS1_INTROUTER0_IN_UART0_USART_IRQ_0                                                (351U)
#define SDLR_C66SS1_INTROUTER0_IN_UART1_USART_IRQ_0                                                (352U)
#define SDLR_C66SS1_INTROUTER0_IN_UART2_USART_IRQ_0                                                (353U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_I3C0_I3C__INT_0                                              (354U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_I3C1_I3C__INT_0                                              (355U)
#define SDLR_C66SS1_INTROUTER0_IN_C66DEBUGSS1_AQCMPINTR_LEVEL_0                                    (356U)
#define SDLR_C66SS1_INTROUTER0_IN_C66SS1_RAT0_C66_RAT_INTR_0                                       (357U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_352                               (358U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_353                               (359U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_354                               (360U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_355                               (361U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_356                               (362U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_357                               (363U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_358                               (364U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_359                               (365U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_360                               (366U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_361                               (367U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_362                               (368U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_363                               (369U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_364                               (370U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_365                               (371U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_366                               (372U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_367                               (373U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_368                               (374U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_369                               (375U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_370                               (376U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_371                               (377U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_372                               (378U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_373                               (379U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_374                               (380U)
#define SDLR_C66SS1_INTROUTER0_IN_NAVSS0_INTR_ROUTER_0_OUTL_INTR_375                               (381U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN0_MCANSS_MCAN_LVL_INT_0                                      (382U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN0_MCANSS_MCAN_LVL_INT_1                                      (383U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (384U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN1_MCANSS_MCAN_LVL_INT_0                                      (385U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN1_MCANSS_MCAN_LVL_INT_1                                      (386U)
#define SDLR_C66SS1_INTROUTER0_IN_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                           (387U)
#define SDLR_C66SS1_INTROUTER0_IN_MLB0_MLBSS_MLB_AHB_INT_0                                         (388U)
#define SDLR_C66SS1_INTROUTER0_IN_MLB0_MLBSS_MLB_AHB_INT_1                                         (389U)
#define SDLR_C66SS1_INTROUTER0_IN_MLB0_MLBSS_MLB_INT_0                                             (390U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_32                                          (391U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_33                                          (392U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_34                                          (393U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_35                                          (394U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_36                                          (395U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_37                                          (396U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_38                                          (397U)
#define SDLR_C66SS1_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_39                                          (398U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_ADC0_GEN_LEVEL_0                                             (399U)
#define SDLR_C66SS1_INTROUTER0_IN_MCU_ADC1_GEN_LEVEL_0                                             (400U)

#ifdef __cplusplus
}
#endif
#endif /* SDLR_C66SS1_INTROUTER0_INTERRUPT_MAP_H_ */

