/********************************************************************
*
* R5FSS0_INTROUTER0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef SDLR_R5FSS0_INTROUTER0_INTERRUPT_MAP_H_
#define SDLR_R5FSS0_INTROUTER0_INTERRUPT_MAP_H_

#include <sdlr.h>
#include <tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: R5FSS0_INTROUTER0
*/

#define SDLR_R5FSS0_INTROUTER0_IN_USB1_OTGIRQ_0                                                    (1U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_IRQ_0                                                       (2U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_IRQ_1                                                       (3U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_IRQ_2                                                       (4U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_IRQ_3                                                       (5U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_IRQ_4                                                       (6U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_IRQ_5                                                       (7U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_IRQ_6                                                       (8U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_IRQ_7                                                       (9U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_LEGACY_PULSE_0                                        (19U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_DOWNSTREAM_PULSE_0                                    (20U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_FLR_PULSE_0                                           (21U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_PHY_LEVEL_0                                           (22U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_LOCAL_LEVEL_0                                         (23U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_ERROR_PULSE_0                                         (24U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_LINK_STATE_PULSE_0                                    (25U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_PWR_STATE_PULSE_0                                     (26U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_PTM_VALID_PULSE_0                                     (27U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_HOT_RESET_PULSE_0                                     (28U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE2_PCIE_CPTS_PEND_0                                           (29U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_0                                  (30U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_1                                  (31U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_2                                  (32U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_3                                  (33U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_4                                  (34U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_5                                  (35U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_6                                  (36U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_HOST_INTR_PEND_7                                  (37U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_0                                  (38U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_1                                  (39U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_2                                  (40U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_3                                  (41U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_4                                  (42U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_5                                  (43U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_6                                  (44U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_HOST_INTR_PEND_7                                  (45U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_TX_SOF_INTR_REQ_0                                 (46U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_TX_SOF_INTR_REQ_1                                 (47U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_RX_SOF_INTR_REQ_0                                 (48U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG0_PR1_RX_SOF_INTR_REQ_1                                 (49U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_TX_SOF_INTR_REQ_0                                 (50U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_TX_SOF_INTR_REQ_1                                 (51U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_RX_SOF_INTR_REQ_0                                 (52U)
#define SDLR_R5FSS0_INTROUTER0_IN_PRU_ICSSG1_PR1_RX_SOF_INTR_REQ_1                                 (53U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_LEGACY_PULSE_0                                        (54U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_DOWNSTREAM_PULSE_0                                    (55U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_FLR_PULSE_0                                           (56U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_PHY_LEVEL_0                                           (57U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_LOCAL_LEVEL_0                                         (58U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_ERROR_PULSE_0                                         (59U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_LINK_STATE_PULSE_0                                    (60U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_PWR_STATE_PULSE_0                                     (61U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_PTM_VALID_PULSE_0                                     (62U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_HOT_RESET_PULSE_0                                     (63U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE3_PCIE_CPTS_PEND_0                                           (64U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB1_HOST_SYSTEM_ERROR_0                                         (65U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_0                                           (68U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_1                                           (69U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_2                                           (70U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_3                                           (71U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_4                                           (72U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_5                                           (73U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_6                                           (74U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_7                                           (75U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_8                                           (76U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_9                                           (77U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_10                                          (78U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_11                                          (79U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_12                                          (80U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_13                                          (81U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_14                                          (82U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPIOMUX_INTRTR0_OUTP_15                                          (83U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_0                     (84U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_1                     (85U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_2                     (86U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_3                     (87U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_4                     (88U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_5                     (89U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_6                     (90U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_7                     (91U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_8                     (92U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_9                     (93U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_10                    (94U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_11                    (95U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_12                    (96U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_13                    (97U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_14                    (98U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_15                    (99U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_16                                         (100U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_17                                         (101U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_18                                         (102U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_19                                         (103U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_20                                         (104U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_21                                         (105U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_22                                         (106U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_23                                         (107U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_24                                         (108U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_25                                         (109U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_26                                         (110U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_27                                         (111U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_28                                         (112U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_29                                         (113U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_30                                         (114U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_31                                         (115U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_ADC0_GEN_LEVEL_0                                             (116U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_ADC1_GEN_LEVEL_0                                             (117U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_CPSW0_STAT_PEND_0                                            (118U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_CPSW0_MDIO_PEND_0                                            (119U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_CPSW0_EVNT_PEND_0                                            (120U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_DCC0_INTR_DONE_LEVEL_0                                       (121U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_DCC1_INTR_DONE_LEVEL_0                                       (122U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_DCC2_INTR_DONE_LEVEL_0                                       (123U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER0_INTR_PEND_0                                           (124U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER1_INTR_PEND_0                                           (125U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER2_INTR_PEND_0                                           (126U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER3_INTR_PEND_0                                           (127U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER4_INTR_PEND_0                                           (128U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER5_INTR_PEND_0                                           (129U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER6_INTR_PEND_0                                           (130U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER7_INTR_PEND_0                                           (131U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER8_INTR_PEND_0                                           (132U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_TIMER9_INTR_PEND_0                                           (133U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_I2C0_POINTRPEND_0                                            (134U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_I2C1_POINTRPEND_0                                            (135U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCSPI0_INTR_SPI_0                                            (136U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCSPI1_INTR_SPI_0                                            (137U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCSPI2_INTR_SPI_0                                            (138U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_UART0_USART_IRQ_0                                            (139U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_I3C0_I3C__INT_0                                              (140U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_I3C1_I3C__INT_0                                              (141U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_FSS0_OSPI_0_OSPI_LVL_INTR_0                                  (142U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_FSS0_OSPI_1_OSPI_LVL_INTR_0                                  (143U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_FSS0_HYPERBUS1P0_0_HPB_INTR_0                                (144U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_FSS0_FSAS_0_OTFA_INTR_ERR_PEND_0                             (145U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_FSS0_FSAS_0_ECC_INTR_ERR_PEND_0                              (146U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_SA2_UL0_SA_UL_PKA_0                                          (147U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_SA2_UL0_SA_UL_TRNG_0                                         (148U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_ESM0_ESM_INT_LOW_LVL_0                                       (149U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_ESM0_ESM_INT_HI_LVL_0                                        (150U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_ESM0_ESM_INT_CFG_LVL_0                                       (151U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_CTRL_MMR0_ACCESS_ERR_0                                       (152U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_CBASS0_LPSC_MCU_COMMON_ERR_INTR_0                            (153U)
#define SDLR_R5FSS0_INTROUTER0_IN_GLUELOGIC_DBG_CBASS_INTR_OR_GLUE_DBG_CBASS_AGG_ERR_INTR_0        (154U)
#define SDLR_R5FSS0_INTROUTER0_IN_GLUELOGIC_FW_CBASS_INTR_OR_GLUE_FW_CBASS_AGG_ERR_INTR_0          (155U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_CBASS0_LPSC_WKUP_COMMON_ERR_INTR_0                          (157U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_I2C0_POINTRPEND_0                                           (158U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_UART0_USART_IRQ_0                                           (159U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_16                                     (160U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_17                                     (161U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_18                                     (162U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_19                                     (163U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_20                                     (164U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_21                                     (165U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_22                                     (166U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_23                                     (167U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_24                                     (168U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_25                                     (169U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_26                                     (170U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_27                                     (171U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_28                                     (172U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_29                                     (173U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_30                                     (174U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_GPIOMUX_INTRTR0_OUTP_31                                     (175U)
#define SDLR_R5FSS0_INTROUTER0_IN_CCDEBUGSS0_AQCMPINTR_LEVEL_0                                     (176U)
#define SDLR_R5FSS0_INTROUTER0_IN_DEBUGSS0_AQCMPINTR_LEVEL_0                                       (177U)
#define SDLR_R5FSS0_INTROUTER0_IN_DEBUGSS1_AQCMPINTR_LEVEL_0                                       (178U)
#define SDLR_R5FSS0_INTROUTER0_IN_C66DEBUGSS0_AQCMPINTR_LEVEL_0                                    (179U)
#define SDLR_R5FSS0_INTROUTER0_IN_DEBUGSS0_CTM_LEVEL_0                                             (180U)
#define SDLR_R5FSS0_INTROUTER0_IN_DEBUGSS1_CTM_LEVEL_0                                             (181U)
#define SDLR_R5FSS0_INTROUTER0_IN_C66DEBUGSS1_AQCMPINTR_LEVEL_0                                    (182U)
#define SDLR_R5FSS0_INTROUTER0_IN_I2C2_POINTRPEND_0                                                (183U)
#define SDLR_R5FSS0_INTROUTER0_IN_I2C3_POINTRPEND_0                                                (184U)
#define SDLR_R5FSS0_INTROUTER0_IN_I2C4_POINTRPEND_0                                                (185U)
#define SDLR_R5FSS0_INTROUTER0_IN_I2C5_POINTRPEND_0                                                (186U)
#define SDLR_R5FSS0_INTROUTER0_IN_I2C6_POINTRPEND_0                                                (187U)
#define SDLR_R5FSS0_INTROUTER0_IN_UART3_USART_IRQ_0                                                (188U)
#define SDLR_R5FSS0_INTROUTER0_IN_UART4_USART_IRQ_0                                                (189U)
#define SDLR_R5FSS0_INTROUTER0_IN_UART5_USART_IRQ_0                                                (190U)
#define SDLR_R5FSS0_INTROUTER0_IN_UART6_USART_IRQ_0                                                (191U)
#define SDLR_R5FSS0_INTROUTER0_IN_UART7_USART_IRQ_0                                                (192U)
#define SDLR_R5FSS0_INTROUTER0_IN_UART8_USART_IRQ_0                                                (193U)
#define SDLR_R5FSS0_INTROUTER0_IN_UART9_USART_IRQ_0                                                (194U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCSPI2_INTR_SPI_0                                                (195U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCSPI3_INTR_SPI_0                                                (196U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCSPI4_INTR_SPI_0                                                (197U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCSPI5_INTR_SPI_0                                                (198U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCSPI6_INTR_SPI_0                                                (199U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCSPI7_INTR_SPI_0                                                (200U)
#define SDLR_R5FSS0_INTROUTER0_IN_I3C0_I3C__INT_0                                                  (201U)
#define SDLR_R5FSS0_INTROUTER0_IN_AASRC0_ERR_LEVEL_0                                               (203U)
#define SDLR_R5FSS0_INTROUTER0_IN_AASRC0_INFIFO_LEVEL_0                                            (204U)
#define SDLR_R5FSS0_INTROUTER0_IN_AASRC0_INGROUP_LEVEL_0                                           (205U)
#define SDLR_R5FSS0_INTROUTER0_IN_AASRC0_OUTFIFO_LEVEL_0                                           (206U)
#define SDLR_R5FSS0_INTROUTER0_IN_AASRC0_OUTGROUP_LEVEL_0                                          (207U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP2_XMIT_INTR_PEND_0                                          (208U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP2_REC_INTR_PEND_0                                           (209U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP3_XMIT_INTR_PEND_0                                          (210U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP3_REC_INTR_PEND_0                                           (211U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP4_XMIT_INTR_PEND_0                                          (212U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP4_REC_INTR_PEND_0                                           (213U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP5_XMIT_INTR_PEND_0                                          (214U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP5_REC_INTR_PEND_0                                           (215U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP6_XMIT_INTR_PEND_0                                          (216U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP6_REC_INTR_PEND_0                                           (217U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP7_XMIT_INTR_PEND_0                                          (218U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP7_REC_INTR_PEND_0                                           (219U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP8_XMIT_INTR_PEND_0                                          (220U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP8_REC_INTR_PEND_0                                           (221U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP9_XMIT_INTR_PEND_0                                          (222U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP9_REC_INTR_PEND_0                                           (223U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP10_XMIT_INTR_PEND_0                                         (224U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP10_REC_INTR_PEND_0                                          (225U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP11_XMIT_INTR_PEND_0                                         (226U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCASP11_REC_INTR_PEND_0                                          (227U)
#define SDLR_R5FSS0_INTROUTER0_IN_GPMC0_GPMC_SINTERRUPT_0                                          (229U)
#define SDLR_R5FSS0_INTROUTER0_IN_ELM0_ELM_POROCPSINTERRUPT_LVL_0                                  (230U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_OTGIRQ_0                                                    (231U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_IRQ_0                                                       (232U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_IRQ_1                                                       (233U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_IRQ_2                                                       (234U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_IRQ_3                                                       (235U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_IRQ_4                                                       (236U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_IRQ_5                                                       (237U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_IRQ_6                                                       (238U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_IRQ_7                                                       (239U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER0_INTR_PEND_0                                               (240U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER1_INTR_PEND_0                                               (241U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER2_INTR_PEND_0                                               (242U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER3_INTR_PEND_0                                               (243U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER4_INTR_PEND_0                                               (244U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER5_INTR_PEND_0                                               (245U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER6_INTR_PEND_0                                               (246U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER7_INTR_PEND_0                                               (247U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER8_INTR_PEND_0                                               (248U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER9_INTR_PEND_0                                               (249U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER10_INTR_PEND_0                                              (250U)
#define SDLR_R5FSS0_INTROUTER0_IN_TIMER11_INTR_PEND_0                                              (251U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_LEGACY_PULSE_0                                        (252U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_DOWNSTREAM_PULSE_0                                    (253U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_FLR_PULSE_0                                           (254U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_PHY_LEVEL_0                                           (255U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_LOCAL_LEVEL_0                                         (256U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_ERROR_PULSE_0                                         (257U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_LINK_STATE_PULSE_0                                    (258U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_PWR_STATE_PULSE_0                                     (259U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_PTM_VALID_PULSE_0                                     (260U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_HOT_RESET_PULSE_0                                     (261U)
#define SDLR_R5FSS0_INTROUTER0_IN_PCIE1_PCIE_CPTS_PEND_0                                           (262U)
#define SDLR_R5FSS0_INTROUTER0_IN_DDR0_DDRSS_CONTROLLER_0                                          (264U)
#define SDLR_R5FSS0_INTROUTER0_IN_DDR0_DDRSS_V2A_OTHER_ERR_LVL_0                                   (265U)
#define SDLR_R5FSS0_INTROUTER0_IN_DDR0_DDRSS_HS_PHY_GLOBAL_ERROR_0                                 (266U)
#define SDLR_R5FSS0_INTROUTER0_IN_DDR0_DDRSS_PLL_FREQ_CHANGE_REQ_0                                 (267U)
#define SDLR_R5FSS0_INTROUTER0_IN_CSI_TX_IF0_CSI_INTERRUPT_0                                       (268U)
#define SDLR_R5FSS0_INTROUTER0_IN_CSI_TX_IF0_CSI_LEVEL_0                                           (269U)
#define SDLR_R5FSS0_INTROUTER0_IN_VPFE0_CCDC_INTR_PEND_0                                           (276U)
#define SDLR_R5FSS0_INTROUTER0_IN_VPFE0_RAT_EXP_INTR_0                                             (277U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_DMSC0_RAT_0_EXP_INTR_0                                      (279U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC0_INTR_DONE_LEVEL_0                                           (280U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC1_INTR_DONE_LEVEL_0                                           (281U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC2_INTR_DONE_LEVEL_0                                           (282U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC3_INTR_DONE_LEVEL_0                                           (283U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC4_INTR_DONE_LEVEL_0                                           (284U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC5_INTR_DONE_LEVEL_0                                           (285U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC6_INTR_DONE_LEVEL_0                                           (286U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC7_INTR_DONE_LEVEL_0                                           (287U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_0                                          (288U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_1                                          (289U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_2                                          (290U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_3                                          (291U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_4                                          (292U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_5                                          (293U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_6                                          (294U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_7                                          (295U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_8                                          (296U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_9                                          (297U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_10                                         (298U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_11                                         (299U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_12                                         (300U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_13                                         (301U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_14                                         (302U)
#define SDLR_R5FSS0_INTROUTER0_IN_CMPEVENT_INTRTR0_OUTP_15                                         (303U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC8_INTR_DONE_LEVEL_0                                           (304U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC9_INTR_DONE_LEVEL_0                                           (305U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC10_INTR_DONE_LEVEL_0                                          (306U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC11_INTR_DONE_LEVEL_0                                          (307U)
#define SDLR_R5FSS0_INTROUTER0_IN_DCC12_INTR_DONE_LEVEL_0                                          (308U)
#define SDLR_R5FSS0_INTROUTER0_IN_MMCSD1_EMMCSDSS_INTR_0                                           (310U)
#define SDLR_R5FSS0_INTROUTER0_IN_MMCSD2_EMMCSDSS_INTR_0                                           (311U)
#define SDLR_R5FSS0_INTROUTER0_IN_UFS0_UFS_INTR_0                                                  (312U)
#define SDLR_R5FSS0_INTROUTER0_IN_SA2_UL0_SA_UL_PKA_0                                              (314U)
#define SDLR_R5FSS0_INTROUTER0_IN_SA2_UL0_SA_UL_TRNG_0                                             (315U)
#define SDLR_R5FSS0_INTROUTER0_IN_ECAP0_ECAP_INT_0                                                 (316U)
#define SDLR_R5FSS0_INTROUTER0_IN_ECAP1_ECAP_INT_0                                                 (317U)
#define SDLR_R5FSS0_INTROUTER0_IN_ECAP2_ECAP_INT_0                                                 (318U)
#define SDLR_R5FSS0_INTROUTER0_IN_GLUELOGIC_SOCA_INT_GLUE_SOCA_INT_0                               (319U)
#define SDLR_R5FSS0_INTROUTER0_IN_GLUELOGIC_SOCB_INT_GLUE_SOCB_INT_0                               (320U)
#define SDLR_R5FSS0_INTROUTER0_IN_USB0_HOST_SYSTEM_ERROR_0                                         (323U)
#define SDLR_R5FSS0_INTROUTER0_IN_GLUELOGIC_MAIN_CBASS_INTR_OR_GLUE_MAIN_CBASS_AGG_ERR_INTR_0      (324U)
#define SDLR_R5FSS0_INTROUTER0_IN_CBASS_INFRA0_DEFAULT_ERR_INTR_0                                  (325U)
#define SDLR_R5FSS0_INTROUTER0_IN_CTRL_MMR0_ACCESS_ERR_0                                           (327U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                                (328U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                                (329U)
#define SDLR_R5FSS0_INTROUTER0_IN_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                                (330U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_GIC_OUTPUT_WAKER_GIC_PWR0_WAKE_REQUEST_0        (332U)
#define SDLR_R5FSS0_INTROUTER0_IN_COMPUTE_CLUSTER0_GIC_OUTPUT_WAKER_GIC_PWR0_WAKE_REQUEST_1        (333U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCAN0_MCANSS_MCAN_LVL_INT_0                                  (336U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCAN0_MCANSS_MCAN_LVL_INT_1                                  (337U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                       (338U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCAN1_MCANSS_MCAN_LVL_INT_0                                  (339U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCAN1_MCANSS_MCAN_LVL_INT_1                                  (340U)
#define SDLR_R5FSS0_INTROUTER0_IN_MCU_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                       (341U)

#ifdef __cplusplus
}
#endif
#endif /* SDLR_R5FSS0_INTROUTER0_INTERRUPT_MAP_H_ */

