/********************************************************************
*
* NAVSS0_UDMASS_INTAGGR_0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef SDLR_NAVSS0_UDMASS_INTAGGR_0_INTERRUPT_MAP_H_
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTERRUPT_MAP_H_

#include <sdlr.h>
#include <tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: NAVSS0_UDMASS_INTAGGR_0
*/

#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MCRC_0_DMA_EVENT_INTR_0              (0U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MCRC_0_DMA_EVENT_INTR_1              (1U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MCRC_0_DMA_EVENT_INTR_2              (2U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MCRC_0_DMA_EVENT_INTR_3              (3U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_0_PEND_INTR_0                (4U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_0_PEND_INTR_1                (5U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_0_PEND_INTR_2                (6U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_0_PEND_INTR_3                (7U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_1_PEND_INTR_0                (8U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_1_PEND_INTR_1                (9U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_1_PEND_INTR_2                (10U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_1_PEND_INTR_3                (11U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_2_PEND_INTR_0                (12U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_2_PEND_INTR_1                (13U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_2_PEND_INTR_2                (14U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_2_PEND_INTR_3                (15U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_3_PEND_INTR_0                (16U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_3_PEND_INTR_1                (17U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_3_PEND_INTR_2                (18U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_3_PEND_INTR_3                (19U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_4_PEND_INTR_0                (20U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_4_PEND_INTR_1                (21U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_4_PEND_INTR_2                (22U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_4_PEND_INTR_3                (23U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_5_PEND_INTR_0                (24U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_5_PEND_INTR_1                (25U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_5_PEND_INTR_2                (26U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_5_PEND_INTR_3                (27U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_6_PEND_INTR_0                (28U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_6_PEND_INTR_1                (29U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_6_PEND_INTR_2                (30U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_6_PEND_INTR_3                (31U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_7_PEND_INTR_0                (32U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_7_PEND_INTR_1                (33U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_7_PEND_INTR_2                (34U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_7_PEND_INTR_3                (35U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_8_PEND_INTR_0                (36U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_8_PEND_INTR_1                (37U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_8_PEND_INTR_2                (38U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_8_PEND_INTR_3                (39U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_9_PEND_INTR_0                (40U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_9_PEND_INTR_1                (41U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_9_PEND_INTR_2                (42U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_9_PEND_INTR_3                (43U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_10_PEND_INTR_0               (44U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_10_PEND_INTR_1               (45U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_10_PEND_INTR_2               (46U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_10_PEND_INTR_3               (47U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_11_PEND_INTR_0               (48U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_11_PEND_INTR_1               (49U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_11_PEND_INTR_2               (50U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_11_PEND_INTR_3               (51U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_40                    (52U)
#define SDLR_TIMESYNC_INTRTR0_OUTL_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_52                    (40U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_41                    (53U)
#define SDLR_TIMESYNC_INTRTR0_OUTL_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_53                    (41U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_42                    (54U)
#define SDLR_TIMESYNC_INTRTR0_OUTL_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_54                    (42U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_43                    (55U)
#define SDLR_TIMESYNC_INTRTR0_OUTL_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_55                    (43U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_44                    (56U)
#define SDLR_TIMESYNC_INTRTR0_OUTL_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_56                    (44U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_45                    (57U)
#define SDLR_TIMESYNC_INTRTR0_OUTL_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_57                    (45U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_46                    (58U)
#define SDLR_TIMESYNC_INTRTR0_OUTL_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_58                    (46U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_47                    (59U)
#define SDLR_TIMESYNC_INTRTR0_OUTL_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_59                    (47U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_24                    (60U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_25                    (61U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_26                    (62U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_27                    (63U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_28                    (64U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_29                    (65U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_30                    (66U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_31                    (67U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_16                     (68U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_17                     (69U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_18                     (70U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_19                     (71U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_20                     (72U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_21                     (73U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_22                     (74U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_23                     (75U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_24                     (76U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_25                     (77U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_26                     (78U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_27                     (79U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_28                     (80U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_29                     (81U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_30                     (82U)
#define SDLR_NAVSS0_UDMASS_INTAGGR_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_31                     (83U)

#ifdef __cplusplus
}
#endif
#endif /* SDLR_NAVSS0_UDMASS_INTAGGR_0_INTERRUPT_MAP_H_ */

