// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2021 NXP
 * All rights reserved.
 *
 */
#ifndef __FLASH_INFO_H__
#define __FLASH_INFO_H__

#include <stdint.h>

#define SLOT_FLASH_SIZE						0x00400000
#define BOOT_FLASH_BASE 					0x30000000
#define BOOT_FLASH_ACT_BASE					(BOOT_FLASH_BASE + SLOT_FLASH_SIZE)
#define BOOT_FLASH_ACT_APP 					(BOOT_FLASH_ACT_BASE + IITP_HEADER_SIZE)
#define BOOT_FLASH_CAND_BASE				(BOOT_FLASH_ACT_BASE + SLOT_FLASH_SIZE)
#define BOOT_FLASH_CAND_APP 				(BOOT_FLASH_CAND_BASE + IITP_HEADER_SIZE)
#define BOOT_FLASH_SCRATCH_BASE				(BOOT_FLASH_CAND_BASE + SLOT_FLASH_SIZE)
#define BOOT_FLASH_SCRATCH_APP				(BOOT_FLASH_SCRATCH_BASE + IITP_HEADER_SIZE)

/* IITP Header Info */
#define IITP_HEADER_IMAGE_SIZE_INFO_SIZE	0x00000100
#define IITP_HEADER_SIGN_INFO_SIZE			0x00000100
#define IITP_HEADER_PADDING_INFO_SIZE		0x00000E00
#define IITP_HEADER_SIZE					(IITP_HEADER_IMAGE_SIZE_INFO_SIZE + IITP_HEADER_SIGN_INFO_SIZE + IITP_HEADER_PADDING_INFO_SIZE)

#define REREMAP_FLASH_BASE					BOOT_FLASH_ACT_BASE

#define FLASH_DEVICE_BASE_ADDR				BOOT_FLASH_BASE
/* BOOT_MAX_IMG_SECTORS must be bigger than the image slot sector number */
#define FLASH_AREA_IMAGE_1_OFFSET			(BOOT_FLASH_ACT_BASE - BOOT_FLASH_BASE)
#define FLASH_AREA_IMAGE_1_SIZE				(BOOT_FLASH_CAND_BASE - BOOT_FLASH_ACT_BASE)
#define FLASH_AREA_IMAGE_2_OFFSET			(FLASH_AREA_IMAGE_1_OFFSET + FLASH_AREA_IMAGE_1_SIZE)
#define FLASH_AREA_IMAGE_2_SIZE				FLASH_AREA_IMAGE_1_SIZE
#define FLASH_AREA_IMAGE_3_OFFSET			(FLASH_AREA_IMAGE_2_OFFSET + FLASH_AREA_IMAGE_2_SIZE)
#define FLASH_AREA_IMAGE_3_SIZE				FLASH_AREA_IMAGE_2_SIZE

#define REMAP_FLAG_ADDRESS 					(REREMAP_FLASH_BASE - 32UL)

#define IMAGE_VERSION_OFFSET 				0x80

int boot_flash_area_read(uint32_t off, void *dst, uint32_t len);
int boot_flash_area_write(uint32_t off, const void *src, uint32_t len);
int boot_flash_area_erase(uint32_t off, uint32_t len);

#endif
