#include "Includes.h"

#define	LIGHTING_GRILL_WHITE_ON		GPIO_PinWrite(BOARD_INITFUNCLIGHTINGGRILLPINS_WHITE_LED_GPIO, BOARD_INITFUNCLIGHTINGGRILLPINS_WHITE_LED_GPIO_PIN, OFF)
#define	LIGHTING_GRILL_WHITE_OFF	GPIO_PinWrite(BOARD_INITFUNCLIGHTINGGRILLPINS_WHITE_LED_GPIO, BOARD_INITFUNCLIGHTINGGRILLPINS_WHITE_LED_GPIO_PIN, ON)
#define	LIGHTING_GRILL_YELLOW_ON	GPIO_PinWrite(BOARD_INITFUNCLIGHTINGGRILLPINS_YELLOW_LED_GPIO, BOARD_INITFUNCLIGHTINGGRILLPINS_YELLOW_LED_GPIO_PIN, OFF)
#define	LIGHTING_GRILL_YELLOW_OFF	GPIO_PinWrite(BOARD_INITFUNCLIGHTINGGRILLPINS_YELLOW_LED_GPIO, BOARD_INITFUNCLIGHTINGGRILLPINS_YELLOW_LED_GPIO_PIN, ON)

#define	CRC_6				0x2C
#define	CRC_6_INIT			0x3F

#define	CRC_8_L_11			0x97
#define	CRC_8_H_11			0xA6
#define	CRC_8_INIT			0xFF

#define	WRITE_BIT			0x01
#define	READ_BIT			0x00

#if 0
#define	LED_H				0x3ff
#define	LED_M				0x1ff
#define	LED_L				0x0
#else
#define	LED_H				0x1ff
#define	LED_M				0x0ff
#define	LED_L				0x0
#endif

#define	LED_ENABLE_0_7		0x62
#define	LED_ENABLE_8_15		0x63

#define	BUS_DERATE_GAIN		0x78
#define	BUS_PULSE_ALL		0x7C
#define	BUS_CURRENT_ALL		0x7D

#define	BUS_BREAK_BYTE		0x00
#define	BUS_SYNC_BYTE		0x55

enum 
{
	BUS_PULSE_0 = 0x40,
	BUS_PULSE_1,
	BUS_PULSE_2,
	BUS_PULSE_3,
	BUS_PULSE_4,
	BUS_PULSE_5,
	BUS_PULSE_6,
	BUS_PULSE_7,
	BUS_PULSE_8,
	BUS_PULSE_9,
	BUS_PULSE_10,
	BUS_PULSE_11,
	BUS_PULSE_12,
	BUS_PULSE_13,
	BUS_PULSE_14,
	BUS_PULSE_15,
	BUS_CURRENT_0,
	BUS_CURRENT_1,
	BUS_CURRENT_2,
	BUS_CURRENT_3,
	BUS_CURRENT_4,
	BUS_CURRENT_5,
	BUS_CURRENT_6,
	BUS_CURRENT_7,
	BUS_CURRENT_8,
	BUS_CURRENT_9,
	BUS_CURRENT_10,
	BUS_CURRENT_11,
	BUS_CURRENT_12,
	BUS_CURRENT_13,
	BUS_CURRENT_14,
	BUS_CURRENT_15,
};

enum 
{
	ELMOS_DEV_ID_0 = 0,
	ELMOS_DEV_ID_1,
	ELMOS_DEV_ID_2,
	ELMOS_DEV_ID_3,
	ELMOS_DEV_ID_4,
	ELMOS_DEV_ID_5,
	ELMOS_DEV_ID_6,
	ELMOS_DEV_ID_7,
	ELMOS_DEV_ID_8,
	ELMOS_DEV_ID_9,
	ELMOS_DEV_ID_10,
	ELMOS_DEV_ID_11,
	ELMOS_DEV_ID_12,
	ELMOS_DEV_ID_13,
	ELMOS_DEV_ID_14,
	ELMOS_DEV_ID_15,
	ELMOS_DEV_ID_16,
	ELMOS_DEV_ID_17,
	ELMOS_DEV_ID_18,
	ELMOS_DEV_ID_19,
	ELMOS_DEV_ID_20,
	ELMOS_DEV_ID_21,
	ELMOS_DEV_ID_22,
	ELMOS_DEV_ID_23,
	ELMOS_DEV_ID_24,
	ELMOS_DEV_ID_25,
	ELMOS_DEV_ID_26,
	ELMOS_DEV_ID_27,
	ELMOS_DEV_ID_28,
	ELMOS_DEV_ID_29,
	ELMOS_DEV_ID_30,
	ELMOS_DEV_ID_31,
};

#define	LED_RIGHT	1
#define	LED_LEFT	2
#define	PWR_WH		0x10
#define	PWR_YEL		0x20

typedef struct {
	uint16_t led_op;
	uint8_t	led_pos;
	uint8_t dev_id;
	uint8_t mem_addr;
	uint8_t num_words;
	uint16_t data;
	uint32_t wtime;	
} elmos_drv_config_t;

typedef struct {
	elmos_drv_config_t * seq_config;
	uint16_t seq_cur;
	uint16_t seq_max;
	uint16_t repTimes;
} led_op_seq_t;

static elmos_drv_config_t turn_right_seq[] = {
//	led_op        led_pos    dev_id         mem_addr   num_words  data  wtime
	OP_LED_TURN_RIGHT, PWR_WH   , 0             , 0           , 0, OFF  , 0 ,
	OP_LED_TURN_RIGHT, PWR_YEL  , 0             , 0           , 0, ON   , 40,
	
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 40,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_H, 40,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 40,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_H, 40,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 40,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_H, 40,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 40,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_H, 40,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 40,

	// remove sig
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0 ,
	OP_LED_TURN_RIGHT, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 1 ,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 0 ,
	OP_LED_TURN_RIGHT, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 1 ,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 0 ,
	OP_LED_TURN_RIGHT, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 1 ,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 0 ,
	OP_LED_TURN_RIGHT, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 1 ,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 0 ,
	OP_LED_TURN_RIGHT, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 1 ,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 0 ,
	OP_LED_TURN_RIGHT, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 1 ,
	OP_LED_TURN_RIGHT, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 0 ,
	OP_LED_TURN_RIGHT, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 1 ,

	OP_LED_TURN_RIGHT, PWR_WH   , 0             , 0           , 0, ON   , 0 ,
	OP_LED_TURN_RIGHT, PWR_YEL  , 0             , 0           , 0, OFF  , 40, 
};

static elmos_drv_config_t turn_left_seq[] = {
//	led_op		  led_pos	 dev_id 		mem_addr   num_words  data	wtime
	OP_LED_TURN_LEFT, PWR_WH   , 0			   , 0		     , 0, OFF  , 0 ,
	OP_LED_TURN_LEFT, PWR_YEL  , 0			   , 0		     , 0, ON   , 40,

	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 40,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_H, 40,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 40,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_H, 40,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 40,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_H, 40,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 40,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_H, 40,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 40,

	// remove sig
	OP_LED_TURN_LEFT, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0 ,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 1 ,
	OP_LED_TURN_LEFT, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 0 ,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 1 ,
	OP_LED_TURN_LEFT, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 0 ,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 1 ,
	OP_LED_TURN_LEFT, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 0 ,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 1 ,
	OP_LED_TURN_LEFT, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 0 ,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 1 ,
	OP_LED_TURN_LEFT, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 0 ,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 1 ,
	OP_LED_TURN_LEFT, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 0 ,
	OP_LED_TURN_LEFT, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 40,

	OP_LED_TURN_LEFT, PWR_WH   , 0             , 0           , 0, ON   , 0 ,
	OP_LED_TURN_LEFT, PWR_YEL  , 0             , 0           , 0, OFF  , 40, 
};

static elmos_drv_config_t remove_seq[] = {
	OP_LED_REMOVE, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0 ,
	OP_LED_REMOVE, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 1 ,
	OP_LED_REMOVE, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 0 ,
	OP_LED_REMOVE, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 1 ,
	OP_LED_REMOVE, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 0 ,
	OP_LED_REMOVE, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 1 ,
	OP_LED_REMOVE, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 0 ,
	OP_LED_REMOVE, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 1 ,
	OP_LED_REMOVE, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 0 ,
	OP_LED_REMOVE, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 1 ,
	OP_LED_REMOVE, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 0 ,
	OP_LED_REMOVE, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 1 ,
	OP_LED_REMOVE, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 0 ,
	OP_LED_REMOVE, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 1 ,
};

static elmos_drv_config_t emergency_seq[] = {
//	led_op		  led_pos	 dev_id 		mem_addr   num_words  data	wtime
	OP_LED_EMERGENCY, PWR_WH	, 0			   , 0		     , 0, OFF  , 0 ,
	OP_LED_EMERGENCY, PWR_YEL	, 0			   , 0		     , 0, ON   , 40,

#if 0
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_0 , 1, LED_M, 0 ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_0 , 1, LED_M, 1 ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_M, 0 ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_M, 1 ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 0 ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 1 ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_M, 0 ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_M, 1 ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 0 ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 1 ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_M, 0 ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_M, 1 ,
#endif
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 500,

	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 500,

	// remove sig
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_EMERGENCY, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 0  ,
	OP_LED_EMERGENCY, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 40 ,

	OP_LED_EMERGENCY, PWR_WH   , 0			   , 0	         , 0, ON   , 0  ,
	OP_LED_EMERGENCY, PWR_YEL  , 0			   , 0		     , 0, OFF  , 40 , 
};

elmos_drv_config_t welcome_seq[] = {
//	led_op		  led_pos	 dev_id 		mem_addr   num_words  data	wtime
	OP_LED_WELCOME, PWR_WH	 , 0             , 0	       , 0, ON	 , 0  ,
	OP_LED_WELCOME, PWR_YEL	 , 0             , 0           , 0, OFF	 , 40 ,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 500,
	
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 500,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_H, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 500,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 500,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_0 , 1, LED_M, 50 ,


 	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 50 ,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_M, 50 ,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_H, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_H, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_H, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_H, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_H, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_H, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_H, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_H, 50 ,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_M, 50 ,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 50 ,

	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_2, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_3, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_4, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_0 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_5, BUS_PULSE_8 , 1, LED_M, 50 ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_M, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_M, 50 ,

	// remove sig
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_6, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_0 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_2 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_4 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_6 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_0, BUS_PULSE_8 , 1, LED_L, 1  ,
	OP_LED_WELCOME, LED_RIGHT, ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 0  ,
	OP_LED_WELCOME, LED_LEFT , ELMOS_DEV_ID_1, BUS_PULSE_10, 1, LED_L, 1  ,

	OP_LED_WELCOME, PWR_WH	 , 0             , 0           , 0, OFF	 , 0  ,
	OP_LED_WELCOME, PWR_YEL	 , 0             , 0           , 0, ON	 , 40 ,
};

static led_op_seq_t led_ctrl;

static uint8_t crc_calc(uint8_t crc, uint8_t rev_poly, uint8_t byte);
static uint8_t calc_rev_poly(uint8_t poly);
static void led_comm_init(void);
static uint8_t led_disp_data(uint8_t led_pos, uint8_t dev_addr, uint8_t mem_addr, uint8_t num_words, uint16_t data);

void DHADemoApp_LG_TURN_RIGHT(void)
{
#if CAN3toCAN_EN == ON
	uint8_t data = ON;
	IlSetECU1_TurnLampRightOperationSig(&data);
#endif
	lightingGrill_OpStart(OP_LED_TURN_RIGHT, 5);
}

void DHADemoApp_LG_TURN_LEFT(void)
{
#if CAN3toCAN_EN == ON
	uint8_t data = ON;
	IlSetECU1_TurnLampLeftOperationSig(&data);
#endif
	lightingGrill_OpStart(OP_LED_TURN_LEFT, 5);
}

void DHADemoApp_LG_EMERGENCY(void)
{
#if CAN3toCAN_EN == ON
	uint8_t data = ON;
	IlSetECU1_LampEmergencyOperationSig(&data);
#endif
	lightingGrill_OpStart(OP_LED_EMERGENCY, 5);
}

void DHADemoApp_LG_WELCOME(void)
{
#if CAN3toCAN_EN == ON
	uint8_t data = ON;
	IlSetECU1_LampWelcomeOperationSig(&data);
#endif
	lightingGrill_OpStart(OP_LED_WELCOME, 5);
}

void lightingGrill_Init(void)
{
	led_comm_init();

	memset(&led_ctrl, 0, sizeof(led_ctrl));

	LIGHTING_GRILL_WHITE_ON;
	LIGHTING_GRILL_YELLOW_OFF;
}

void lightingGrill_OpStart(uint16_t led_op, uint16_t repTimes)
{
	elmos_drv_config_t * drv_cfg, * drv_cfg_next;
	uint16_t cnt;
	
	memset(&led_ctrl, 0, sizeof(led_ctrl));

	switch (led_op)
	{
		case OP_LED_TURN_RIGHT:
			led_ctrl.seq_config = turn_right_seq;
			break;
		case OP_LED_TURN_LEFT:
			led_ctrl.seq_config = turn_left_seq;
			break;
		case OP_LED_EMERGENCY:
			led_ctrl.seq_config = emergency_seq;
			break;
		case OP_LED_WELCOME:
			led_ctrl.seq_config = welcome_seq;
			break;
		default:
			APPINFO_PRINTF("[%s] lighting grill command error : 0x%x\r\n", __func__, led_op);
			assert(0);
			break;
	}

	led_ctrl.repTimes = repTimes;
	
	cnt = 0;
	do {
		drv_cfg = &led_ctrl.seq_config[cnt];
		drv_cfg_next = &led_ctrl.seq_config[cnt + 1];
		cnt++;
	} while (drv_cfg->led_op == drv_cfg_next->led_op);
	led_ctrl.seq_max = cnt;

	SetSoftTimer(STIMER_IOCTRL_LIGHTING_GRILL_LED_OP, DHAUTO_SOFTTIME_50MS, lightingGrill_OpSeq);

	APPINFO_PRINTF("[%s] led_op_name=%x led_pos=%d seq_max=%d \r\n", __func__, led_ctrl.seq_config->led_op, led_ctrl.seq_config->led_pos, led_ctrl.seq_max);
}

void lightingGrill_OpSeq(void)
{
	uint16_t pos, led_op_cur;
	elmos_drv_config_t * drv_cfg;

	KillSoftTimer(STIMER_IOCTRL_LIGHTING_GRILL_LED_OP);
	
#if 0
#if 0
	pos = led_ctrl.seq_cur;
	drv_cfg_cur = &led_ctrl.seq_config[pos];
	led_op_cur = drv_cfg_cur->led_op;
#else
	pos = led_ctrl.seq_cur;
	led_op_cur = led_ctrl.seq_config->led_op;
#endif
	do {
		drv_cfg = &led_ctrl.seq_config[pos];
		if (led_op_cur == drv_cfg->led_op)
		{
			led_disp_data(drv_cfg->led_pos, drv_cfg->dev_id, drv_cfg->mem_addr, drv_cfg->data, drv_cfg->data);
			APPINFO_PRINTF("[%s] op_name=%x curr=%02d repeat=%02d \r\n", __func__, led_ctrl.seq_config->led_op, pos, led_ctrl.repTimes); 
			pos++;
		}
		else
		{
			break;
		}
	} while (drv_cfg->wtime == 0);
	led_ctrl.seq_cur = pos - 1;
#endif

	pos = led_ctrl.seq_cur;
	drv_cfg = &led_ctrl.seq_config[pos];
	//led_op_cur = drv_cfg->led_op;

	while (1)
	{
		if ((drv_cfg->led_pos == PWR_WH) || (drv_cfg->led_pos == PWR_YEL))
		{
			if (drv_cfg->led_pos == PWR_WH)
			{
				if (drv_cfg->data == OFF)	LIGHTING_GRILL_WHITE_OFF;
				else	LIGHTING_GRILL_WHITE_ON;
			}
			else if (drv_cfg->led_pos == PWR_YEL)
			{
				if (drv_cfg->data == OFF)	LIGHTING_GRILL_YELLOW_OFF;
				else	LIGHTING_GRILL_YELLOW_ON;
			}
			else
			{
			}
		}
		else
		{
			led_disp_data(drv_cfg->led_pos, drv_cfg->dev_id, drv_cfg->mem_addr, drv_cfg->num_words, drv_cfg->data);
		}
		//APPINFO_PRINTF("[%02d] %02d %02x\r\n", pos, drv_cfg->dev_id, drv_cfg->mem_addr);
		pos++;

		//if (drv_cfg->wtime != 0)
		if (drv_cfg->wtime > 1)
		{
			break;
		}
		else
		{
			if (drv_cfg->wtime != 0)	SDK_DelayAtLeastUs(500, SDK_DEVICE_MAXIMUM_CPU_CLOCK_FREQUENCY);
			drv_cfg++;
		}
	}
	led_ctrl.seq_cur = pos - 1;

	//APPINFO_PRINTF("[%s] op_name=%x curr=%02d repeat=%02d \r\n", __func__, led_ctrl.seq_config->led_op, led_ctrl.seq_cur, led_ctrl.repTimes);

	if (pos < led_ctrl.seq_max)
	{
		SetSoftTimer(STIMER_IOCTRL_LIGHTING_GRILL_LED_OP, drv_cfg->wtime, lightingGrill_OpSeq);
		led_ctrl.seq_cur++;
	}
	else
	{
		if (led_ctrl.repTimes != 0)
		{
			led_ctrl.repTimes--;
			led_ctrl.seq_cur = 0;
			pos = 0;
			drv_cfg = &led_ctrl.seq_config[pos];

			if (led_ctrl.repTimes != 0)
				SetSoftTimer(STIMER_IOCTRL_LIGHTING_GRILL_LED_OP, 5, lightingGrill_OpSeq);		
		}

		APPINFO_PRINTF("[%s] op_name=%x curr=%02d repeat=%02d \r\n", __func__, led_ctrl.seq_config->led_op, led_ctrl.seq_cur, led_ctrl.repTimes);
	}
}

static void led_comm_init(void)
{
	lpuart_config_t config;

	LPUART_GetDefaultConfig(&config);
	config.baudRate_Bps = 500000;
	config.parityMode = kLPUART_ParityEven;
	config.stopBitCount = kLPUART_OneStopBit;
	config.enableTx     = true;
	config.enableRx     = true;

	LPUART_Init(LPUART11, &config, CLOCK_GetRootClockFreq(kCLOCK_Root_Lpuart11));
	LPUART_Init(LPUART10, &config, CLOCK_GetRootClockFreq(kCLOCK_Root_Lpuart10));
}

static uint8_t led_disp_data(uint8_t led_pos, uint8_t dev_addr, uint8_t mem_addr, uint8_t num_words, uint16_t data)
{
	uint8_t i;
	uint8_t crc, data_len, error_data[10], buf[20];
	LPUART_Type * lpuart;
	clock_root_t root;

	if (led_pos == LED_LEFT)
	{
		lpuart = LPUART10;
		root = kCLOCK_Root_Lpuart10;
	}
	else if (led_pos == LED_RIGHT)
	{
		lpuart = LPUART11;
		root = kCLOCK_Root_Lpuart11;
	}
	else
	{
		APPINFO_PRINTF("[%s] led position value is not valid ...\r\n", __func__);
		assert(0);
	}

	memset(error_data, 0, sizeof(error_data));
	memset(buf, 0, sizeof(buf));

	buf[0] = BUS_BREAK_BYTE;
	LPUART_SetBaudRate(lpuart, 399881, CLOCK_GetRootClockFreq(root));
	LPUART_WriteBlocking(lpuart, &buf[0], 1);

	buf[0] = BUS_SYNC_BYTE;
	buf[1] = mem_addr;
	buf[2] = (dev_addr & 0x1f) | (WRITE_BIT << 5) | (((num_words-1) & 0x03) << 6);

	crc = crc_calc(CRC_6_INIT, calc_rev_poly(CRC_6), buf[1]);
	crc = crc_calc(crc, calc_rev_poly(CRC_6), buf[2]);
	crc = crc_calc(crc, calc_rev_poly(CRC_6), (((num_words-1)& 0x0c) >> 2));
	buf[3] = (crc << 2) | (((num_words-1) & 0x0c) >> 2);
	LPUART_SetBaudRate(lpuart, 500000, CLOCK_GetRootClockFreq(root));
	LPUART_WriteBlocking(lpuart, &buf[0], 4);

	SDK_DelayAtLeastUs(100, SDK_DEVICE_MAXIMUM_CPU_CLOCK_FREQUENCY);

#if (LIGHTING_GRILL_INSTALLED == ON)
	LPUART_ReadBlocking(lpuart, error_data, 6);
	if(((error_data[5] & 0x0f) != 0x00) || ((error_data[5] & 0x07) != 0x00) || ((error_data[5] & 0x03) != 0x00))
	{
		APPINFO_PRINTF("header error data : 0x%x\r\n", error_data[5]);
		return 0;
    }
#endif

	crc = 0;

	if(num_words <= 4)
	{
		data_len = num_words + 1;
	}
	else if(num_words <= 8)
	{
		data_len = num_words + 2;
	}
	else if(num_words <= 12)
	{
		data_len = num_words + 3;
	}
	else if(num_words <= 16)
	{
		data_len = num_words + 4;
	}

	buf[0] = (uint8_t)(data & 0xFF);
	buf[1] = (uint8_t)((data & 0x300)>>8);

	if(num_words < 11)
	{
		crc = crc_calc(CRC_8_INIT, calc_rev_poly(CRC_8_L_11), buf[0]);
		for(i=1; i<data_len; i++)
		{
			crc = crc_calc(crc, calc_rev_poly(CRC_8_L_11), buf[i]);
		}
		buf[i] = crc;
	}
	else
	{
		crc = crc_calc(CRC_8_INIT, calc_rev_poly(CRC_8_H_11), buf[0]);
		for(i=1; i<data_len; i++)
		{
			crc = crc_calc(crc, calc_rev_poly(CRC_8_H_11), buf[i]);
		}
        buf[i] = crc;
	}
	
	LPUART_WriteBlocking(lpuart, &buf[0], (data_len + 1));
	
#if 0
	SDK_DelayAtLeastUs(200, SDK_DEVICE_MAXIMUM_CPU_CLOCK_FREQUENCY);

	memcpy(error_data, data_clear, sizeof(error_data));
	LPUART_ReadBlocking(LPUART12, error_data, (data_len+2));
	if(((error_data[data_len+2] & 0x0f) != 0x00) || ((error_data[data_len+2] & 0x07) != 0x00) || ((error_data[data_len+2] & 0x03) != 0x00))
	{
		APPINFO_PRINTF("data error data : 0x%x\r\n", error_data[data_len+2]);
		return 0;
	}
#endif

    return 1;
}

uint8_t crc_calc(uint8_t crc, uint8_t rev_poly, uint8_t byte)
{
	uint8_t n;

	for(n = 0; n < 8; n++)
	{
		if((crc ^ byte) & 1)
		{
			crc = (crc >> 1) ^ rev_poly;
		}
		else
		{
			crc = (crc >> 1);
		}
		byte >>= 1;
	}

	return crc;
}

uint8_t calc_rev_poly(uint8_t poly)
{
	uint8_t rev_poly = 1;

	while(poly > 1)
	{
		rev_poly = (rev_poly << 1) | (poly & 1);
		poly >>= 1;
	}

	return rev_poly;
}

