/******************************************************************************
 *                                                                             *
 * module name       :MMALIB                                                   *
 *                                                                             *
 * module descripton :Matrix Multiply Accelerator Library module for C7x+MMA   *
 *                                                                             *
 * Copyright (C) 2017-2018 Texas Instruments Incorporated - http://www.ti.com/ *
 * ALL RIGHTS RESERVED                                                         *
 *                                                                             *
 ******************************************************************************/

/**
******************************************************************************
*  @file     MMALIB_CNN_pixelShuffle_row_ixX_ixX_oxX_idat.c
*
*  @brief    File to have static test data related content
*
*  @version  0.1 - Jan 2018 : Initial Version - Template [PKS]
*
*******************************************************************************
*/

#include "MMALIB_CNN_pixelShuffle_row_ixX_ixX_oxX_idat.h"

/*This file is autogenerated*/
/*Please do not edit*/

#include "test_data/extended_test_cases/staticRefCase0_i8s_i8s_i8s.h"

/* #if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 100) || (TEST_CATEGORY ==
 * 200) || (EXTENDED_TEST_CASE == 0)) #include
 * "test_data/extended_test_cases/staticRefCase0_i8s_i8s_i8s.h" #endif */

static pixelShuffle_row_ixX_ixX_oxX_testParams_t testParams[] = {
    {
        STATIC, // testPattern
        staticRefIn_case0_i8s_i8s_i8s,
        staticRefKernel_case0_i8s_i8s_i8s,
        staticRefOutput_case0_i8s_i8s_i8s,
        NULL,
        NULL,
        NULL,
        3,                 // kernelWidth
        3,                 // kernelHeight
        1,                 // strideWidth
        1,                 // strideHeight
        1,                 // dilationHeight
        1,                 // dilationWidth
        2,                 // upscaleFactor
        256,               // inWidth
        1,                 // pad
        256,               // maxHeight
        1600,              // inChOffset
        1548,              // validColsIn
        2305,              // kDim
        2624,              // pitchA
        64,                // numOfOutputChKerBuf
        3136,              // pitchC
        64,                // subMChannels
        256,               // numInChannels
        64,                // numOutChannels
        14,                // qShift
        20,                // biasB
        MMALIB_SATURATION, // activationType
        MMALIB_INT8,       // dataTypeA
        MMALIB_INT8,       // dataTypeB
        MMALIB_INT8,       // dataTypeC
        MMALIB_LINEAR,     // mode
        0,                 // circularOffset
        64,                // totalN
        64,                // subN
        0,                 // validColsPerRowIn
        0,                 // validRowsIn
        0,                 // outputPitchPerRow
        0,                 // inputPitchPerRow
        1548,              // validColsInlast
        0,                 // validColsPerRowInlast
        0,                 // validRowsInlast
        MMALIB_TEST_OUTPUT_MSMC,
        0,
    },

};

/*
 *  Sends the test parameter structure and number of tests
 */
void pixelShuffle_row_ixX_ixX_oxX_getTestParams (
    pixelShuffle_row_ixX_ixX_oxX_testParams_t **params,
    int32_t *                                   numTests)
{
   *params   = testParams;
   *numTests = sizeof (testParams) / sizeof (pixelShuffle_row_ixX_ixX_oxX_testParams_t);
}

/* ======================================================================== */
/*                       End of file                                        */
/* ------------------------------------------------------------------------ */
/*            Copyright (c) 2016 Texas Instruments, Incorporated.           */
/*                           All Rights Reserved.                           */
/* ======================================================================== */
