/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/* GPIO_LPSR_01 (coord R6), CAN3_RX/U42[4] */
/* Routed pin properties */
#define BOARD_INITCANPINS_CAN_RX_PERIPHERAL                                 CAN3   /*!< Peripheral name */
#define BOARD_INITCANPINS_CAN_RX_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_LPSR_00 (coord N6), CAN3_TX/U42[1] */
/* Routed pin properties */
#define BOARD_INITCANPINS_CAN_TX_PERIPHERAL                                 CAN3   /*!< Peripheral name */
#define BOARD_INITCANPINS_CAN_TX_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_07 (coord T17), USB_OTG2_PWR/WL_DEV_WAKE/U354[10]/J10[2] */
/* Routed pin properties */
#define BOARD_INITCANPINS_CANFD_RX_PERIPHERAL                               CAN1   /*!< Peripheral name */
#define BOARD_INITCANPINS_CANFD_RX_SIGNAL                                     RX   /*!< Signal name */

/* GPIO_AD_06 (coord N13), USB_OTG2_OC/U18[A2]/J9[10]/AUD_INT */
/* Routed pin properties */
#define BOARD_INITCANPINS_CANFD_TX_PERIPHERAL                               CAN1   /*!< Peripheral name */
#define BOARD_INITCANPINS_CANFD_TX_SIGNAL                                     TX   /*!< Signal name */

/* GPIO_AD_14 (coord N14), SPDIF_EXT_CLK/CAN_STBY/J9[16] */
/* Routed pin properties */
#define BOARD_INITCANPINS_CAN_FD_STBY_PERIPHERAL                           GPIO9   /*!< Peripheral name */
#define BOARD_INITCANPINS_CAN_FD_STBY_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITCANPINS_CAN_FD_STBY_CHANNEL                                13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCANPINS_CAN_FD_STBY_GPIO                                 GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITCANPINS_CAN_FD_STBY_GPIO_PIN                               13U   /*!< GPIO pin number */
#define BOARD_INITCANPINS_CAN_FD_STBY_GPIO_PIN_MASK                  (1U << 13U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCanPins(void);                 /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
